name: Tests

on: [push, pull_request]

jobs:
  build-test:
    name: Build Test
    runs-on: ubuntu-latest
    container: devkitpro/devkitppc:20240612
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Test build
      run: |
        make -f Makefile.gc clean
        make -f Makefile.gc -j2
        
    - name: Verify output
      run: |
        ls -lh executables/mamegc-gc.dol
        test -f executables/mamegc-gc.dol || exit 1
        
    - name: Test clean
      run: |
        make -f Makefile.gc clean
        test ! -f executables/mamegc-gc.dol || exit 1

  pgo-build-test:
    name: PGO Build Test
    runs-on: ubuntu-latest
    container: devkitpro/devkitppc:20240612
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Test PGO generate build
      run: |
        make -f Makefile.gc pgo-generate -j2
        
    - name: Verify PGO output
      run: |
        ls -lh executables/mamegc-gc_pgo_gen.dol
        test -f executables/mamegc-gc_pgo_gen.dol || exit 1
        
    - name: Test PGO clean
      run: |
        make -f Makefile.gc pgo-clean
        test ! -f executables/mamegc-gc_pgo_gen.dol || exit 1
